on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: test

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest}
          - {os: macos-latest}
          - {os: windows-latest}

    name: ${{matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Format check
        run: cargo fmt --check
      - name: Check
        run: cargo check --release --all-features
      - name: Test
        run: cargo test
